// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.9.0
// source: etcd_bridge_roles.proto

package etcdbridgeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRoleForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role     string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *AddRoleForUserRequest) Reset() {
	*x = AddRoleForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoleForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleForUserRequest) ProtoMessage() {}

func (x *AddRoleForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleForUserRequest.ProtoReflect.Descriptor instead.
func (*AddRoleForUserRequest) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{0}
}

func (x *AddRoleForUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddRoleForUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Roles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role   string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Path   string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Action []string `protobuf:"bytes,3,rep,name=action,proto3" json:"action,omitempty"`
}

func (x *Roles) Reset() {
	*x = Roles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Roles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roles) ProtoMessage() {}

func (x *Roles) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roles.ProtoReflect.Descriptor instead.
func (*Roles) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{1}
}

func (x *Roles) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Roles) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Roles) GetAction() []string {
	if x != nil {
		return x.Action
	}
	return nil
}

type RolesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role   string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Path   string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Action []string `protobuf:"bytes,3,rep,name=action,proto3" json:"action,omitempty"`
}

func (x *RolesRequest) Reset() {
	*x = RolesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesRequest) ProtoMessage() {}

func (x *RolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesRequest.ProtoReflect.Descriptor instead.
func (*RolesRequest) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{2}
}

func (x *RolesRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RolesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RolesRequest) GetAction() []string {
	if x != nil {
		return x.Action
	}
	return nil
}

type RolesLisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchKey string `protobuf:"bytes,1,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	Page      int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int64  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *RolesLisRequest) Reset() {
	*x = RolesLisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesLisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesLisRequest) ProtoMessage() {}

func (x *RolesLisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesLisRequest.ProtoReflect.Descriptor instead.
func (*RolesLisRequest) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{3}
}

func (x *RolesLisRequest) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *RolesLisRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RolesLisRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RolesListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*Roles `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *RolesListResponse) Reset() {
	*x = RolesListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesListResponse) ProtoMessage() {}

func (x *RolesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesListResponse.ProtoReflect.Descriptor instead.
func (*RolesListResponse) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{4}
}

func (x *RolesListResponse) GetData() []*Roles {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RolesListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RolesPermissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role   string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *RolesPermissions) Reset() {
	*x = RolesPermissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesPermissions) ProtoMessage() {}

func (x *RolesPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesPermissions.ProtoReflect.Descriptor instead.
func (*RolesPermissions) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{5}
}

func (x *RolesPermissions) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RolesPermissions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RolesPermissions) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type RoleDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []*RolesPermissions `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *RoleDelRequest) Reset() {
	*x = RoleDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDelRequest) ProtoMessage() {}

func (x *RoleDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDelRequest.ProtoReflect.Descriptor instead.
func (*RoleDelRequest) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{6}
}

func (x *RoleDelRequest) GetRoles() []*RolesPermissions {
	if x != nil {
		return x.Roles
	}
	return nil
}

type DelRoleForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role     string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *DelRoleForUserRequest) Reset() {
	*x = DelRoleForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRoleForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRoleForUserRequest) ProtoMessage() {}

func (x *DelRoleForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRoleForUserRequest.ProtoReflect.Descriptor instead.
func (*DelRoleForUserRequest) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{7}
}

func (x *DelRoleForUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DelRoleForUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RolesPermissionsDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []*RolesPermissions `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *RolesPermissionsDelRequest) Reset() {
	*x = RolesPermissionsDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesPermissionsDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesPermissionsDelRequest) ProtoMessage() {}

func (x *RolesPermissionsDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesPermissionsDelRequest.ProtoReflect.Descriptor instead.
func (*RolesPermissionsDelRequest) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{8}
}

func (x *RolesPermissionsDelRequest) GetRoles() []*RolesPermissions {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RolesPermissionsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*RolesPermissions `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total int64               `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *RolesPermissionsListResponse) Reset() {
	*x = RolesPermissionsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcd_bridge_roles_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesPermissionsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesPermissionsListResponse) ProtoMessage() {}

func (x *RolesPermissionsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_bridge_roles_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesPermissionsListResponse.ProtoReflect.Descriptor instead.
func (*RolesPermissionsListResponse) Descriptor() ([]byte, []int) {
	return file_etcd_bridge_roles_proto_rawDescGZIP(), []int{9}
}

func (x *RolesPermissionsListResponse) GetData() []*RolesPermissions {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RolesPermissionsListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_etcd_bridge_roles_proto protoreflect.FileDescriptor

var file_etcd_bridge_roles_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x74, 0x63, 0x64, 0x5f,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x22, 0x47, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6c,
	0x65, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x47, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x4c, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x51, 0x0a, 0x11, 0x52,
	0x6f, 0x6c, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x52,
	0x0a, 0x10, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x15, 0x44, 0x65, 0x6c,
	0x52, 0x6f, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x51, 0x0a, 0x1a, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x33, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x67, 0x0a, 0x1c, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x13,
	0x5a, 0x11, 0x2e, 0x3b, 0x65, 0x74, 0x63, 0x64, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_etcd_bridge_roles_proto_rawDescOnce sync.Once
	file_etcd_bridge_roles_proto_rawDescData = file_etcd_bridge_roles_proto_rawDesc
)

func file_etcd_bridge_roles_proto_rawDescGZIP() []byte {
	file_etcd_bridge_roles_proto_rawDescOnce.Do(func() {
		file_etcd_bridge_roles_proto_rawDescData = protoimpl.X.CompressGZIP(file_etcd_bridge_roles_proto_rawDescData)
	})
	return file_etcd_bridge_roles_proto_rawDescData
}

var file_etcd_bridge_roles_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_etcd_bridge_roles_proto_goTypes = []interface{}{
	(*AddRoleForUserRequest)(nil),        // 0: etcd_bridge.AddRoleForUserRequest
	(*Roles)(nil),                        // 1: etcd_bridge.Roles
	(*RolesRequest)(nil),                 // 2: etcd_bridge.RolesRequest
	(*RolesLisRequest)(nil),              // 3: etcd_bridge.RolesLisRequest
	(*RolesListResponse)(nil),            // 4: etcd_bridge.RolesListResponse
	(*RolesPermissions)(nil),             // 5: etcd_bridge.RolesPermissions
	(*RoleDelRequest)(nil),               // 6: etcd_bridge.RoleDelRequest
	(*DelRoleForUserRequest)(nil),        // 7: etcd_bridge.DelRoleForUserRequest
	(*RolesPermissionsDelRequest)(nil),   // 8: etcd_bridge.RolesPermissionsDelRequest
	(*RolesPermissionsListResponse)(nil), // 9: etcd_bridge.RolesPermissionsListResponse
}
var file_etcd_bridge_roles_proto_depIdxs = []int32{
	1, // 0: etcd_bridge.RolesListResponse.data:type_name -> etcd_bridge.Roles
	5, // 1: etcd_bridge.RoleDelRequest.roles:type_name -> etcd_bridge.RolesPermissions
	5, // 2: etcd_bridge.RolesPermissionsDelRequest.roles:type_name -> etcd_bridge.RolesPermissions
	5, // 3: etcd_bridge.RolesPermissionsListResponse.data:type_name -> etcd_bridge.RolesPermissions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_etcd_bridge_roles_proto_init() }
func file_etcd_bridge_roles_proto_init() {
	if File_etcd_bridge_roles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_etcd_bridge_roles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoleForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Roles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesLisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesPermissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRoleForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesPermissionsDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcd_bridge_roles_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesPermissionsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_etcd_bridge_roles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_etcd_bridge_roles_proto_goTypes,
		DependencyIndexes: file_etcd_bridge_roles_proto_depIdxs,
		MessageInfos:      file_etcd_bridge_roles_proto_msgTypes,
	}.Build()
	File_etcd_bridge_roles_proto = out.File
	file_etcd_bridge_roles_proto_rawDesc = nil
	file_etcd_bridge_roles_proto_goTypes = nil
	file_etcd_bridge_roles_proto_depIdxs = nil
}
