// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.9.0
// source: server_info.proto

package etcdbridgeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSsl     int32  `protobuf:"varint,1,opt,name=is_ssl,json=isSsl,proto3" json:"is_ssl,omitempty"`
	CaCerPath string `protobuf:"bytes,2,opt,name=ca_cer_path,json=caCerPath,proto3" json:"ca_cer_path,omitempty"`
	CertPath  string `protobuf:"bytes,3,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"`
	KeyPath   string `protobuf:"bytes,4,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	Host      string `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Type      int64  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Username  string `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password  string `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Id        int64  `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_server_info_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetIsSsl() int32 {
	if x != nil {
		return x.IsSsl
	}
	return 0
}

func (x *ServerInfo) GetCaCerPath() string {
	if x != nil {
		return x.CaCerPath
	}
	return ""
}

func (x *ServerInfo) GetCertPath() string {
	if x != nil {
		return x.CertPath
	}
	return ""
}

func (x *ServerInfo) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *ServerInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerInfo) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ServerInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServerInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ServerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SaveServerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSsl     int32  `protobuf:"varint,1,opt,name=is_ssl,json=isSsl,proto3" json:"is_ssl,omitempty"`
	CaCerPath string `protobuf:"bytes,2,opt,name=ca_cer_path,json=caCerPath,proto3" json:"ca_cer_path,omitempty"`
	CertPath  string `protobuf:"bytes,3,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"`
	KeyPath   string `protobuf:"bytes,4,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	Host      string `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Type      int64  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Username  string `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password  string `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Id        int64  `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SaveServerInfoRequest) Reset() {
	*x = SaveServerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveServerInfoRequest) ProtoMessage() {}

func (x *SaveServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveServerInfoRequest.ProtoReflect.Descriptor instead.
func (*SaveServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_server_info_proto_rawDescGZIP(), []int{1}
}

func (x *SaveServerInfoRequest) GetIsSsl() int32 {
	if x != nil {
		return x.IsSsl
	}
	return 0
}

func (x *SaveServerInfoRequest) GetCaCerPath() string {
	if x != nil {
		return x.CaCerPath
	}
	return ""
}

func (x *SaveServerInfoRequest) GetCertPath() string {
	if x != nil {
		return x.CertPath
	}
	return ""
}

func (x *SaveServerInfoRequest) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *SaveServerInfoRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SaveServerInfoRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SaveServerInfoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SaveServerInfoRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SaveServerInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelSaveServerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DelSaveServerInfoRequest) Reset() {
	*x = DelSaveServerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSaveServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSaveServerInfoRequest) ProtoMessage() {}

func (x *DelSaveServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSaveServerInfoRequest.ProtoReflect.Descriptor instead.
func (*DelSaveServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_server_info_proto_rawDescGZIP(), []int{2}
}

func (x *DelSaveServerInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_server_info_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ServerInfoLisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchKey string `protobuf:"bytes,1,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	Page      int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int64  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ServerInfoLisRequest) Reset() {
	*x = ServerInfoLisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoLisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoLisRequest) ProtoMessage() {}

func (x *ServerInfoLisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoLisRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoLisRequest) Descriptor() ([]byte, []int) {
	return file_server_info_proto_rawDescGZIP(), []int{4}
}

func (x *ServerInfoLisRequest) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *ServerInfoLisRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ServerInfoLisRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ServerInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*ServerInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total int64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ServerInfoListResponse) Reset() {
	*x = ServerInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoListResponse) ProtoMessage() {}

func (x *ServerInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoListResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoListResponse) Descriptor() ([]byte, []int) {
	return file_server_info_proto_rawDescGZIP(), []int{5}
}

func (x *ServerInfoListResponse) GetData() []*ServerInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerInfoListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_server_info_proto protoreflect.FileDescriptor

var file_server_info_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x22, 0xeb, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x73, 0x73, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x69, 0x73, 0x53, 0x73, 0x6c, 0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x61, 0x5f, 0x63, 0x65, 0x72,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x43,
	0x65, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x65, 0x72, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf6,
	0x01, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x73,
	0x73, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x53, 0x73, 0x6c, 0x12,
	0x1e, 0x0a, 0x0b, 0x63, 0x61, 0x5f, 0x63, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x43, 0x65, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x65, 0x72, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08,
	0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x53, 0x61,
	0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x14, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x5b, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x74,
	0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x65, 0x74, 0x63, 0x64, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_info_proto_rawDescOnce sync.Once
	file_server_info_proto_rawDescData = file_server_info_proto_rawDesc
)

func file_server_info_proto_rawDescGZIP() []byte {
	file_server_info_proto_rawDescOnce.Do(func() {
		file_server_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_info_proto_rawDescData)
	})
	return file_server_info_proto_rawDescData
}

var file_server_info_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_info_proto_goTypes = []interface{}{
	(*ServerInfo)(nil),               // 0: etcd_bridge.ServerInfo
	(*SaveServerInfoRequest)(nil),    // 1: etcd_bridge.SaveServerInfoRequest
	(*DelSaveServerInfoRequest)(nil), // 2: etcd_bridge.DelSaveServerInfoRequest
	(*GetServerInfoRequest)(nil),     // 3: etcd_bridge.GetServerInfoRequest
	(*ServerInfoLisRequest)(nil),     // 4: etcd_bridge.ServerInfoLisRequest
	(*ServerInfoListResponse)(nil),   // 5: etcd_bridge.ServerInfoListResponse
}
var file_server_info_proto_depIdxs = []int32{
	0, // 0: etcd_bridge.ServerInfoListResponse.data:type_name -> etcd_bridge.ServerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_info_proto_init() }
func file_server_info_proto_init() {
	if File_server_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveServerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSaveServerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoLisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_info_proto_goTypes,
		DependencyIndexes: file_server_info_proto_depIdxs,
		MessageInfos:      file_server_info_proto_msgTypes,
	}.Build()
	File_server_info_proto = out.File
	file_server_info_proto_rawDesc = nil
	file_server_info_proto_goTypes = nil
	file_server_info_proto_depIdxs = nil
}
