// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.9.0
// source: sync_conf.proto

package etcdbridgeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceServerId int64       `protobuf:"varint,2,opt,name=source_server_id,json=sourceServerId,proto3" json:"source_server_id,omitempty"`
	TargetServerId int64       `protobuf:"varint,3,opt,name=target_server_id,json=targetServerId,proto3" json:"target_server_id,omitempty"`
	Status         int32       `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	SourceServer   *ServerInfo `protobuf:"bytes,5,opt,name=source_server,json=sourceServer,proto3" json:"source_server,omitempty"`
	TargetServer   *ServerInfo `protobuf:"bytes,6,opt,name=target_server,json=targetServer,proto3" json:"target_server,omitempty"`
	WatcherKey     string      `protobuf:"bytes,7,opt,name=watcher_key,json=watcherKey,proto3" json:"watcher_key,omitempty"`
	SyncAllTime    int64       `protobuf:"varint,8,opt,name=sync_all_time,json=syncAllTime,proto3" json:"sync_all_time,omitempty"`
}

func (x *SyncConf) Reset() {
	*x = SyncConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConf) ProtoMessage() {}

func (x *SyncConf) ProtoReflect() protoreflect.Message {
	mi := &file_sync_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConf.ProtoReflect.Descriptor instead.
func (*SyncConf) Descriptor() ([]byte, []int) {
	return file_sync_conf_proto_rawDescGZIP(), []int{0}
}

func (x *SyncConf) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncConf) GetSourceServerId() int64 {
	if x != nil {
		return x.SourceServerId
	}
	return 0
}

func (x *SyncConf) GetTargetServerId() int64 {
	if x != nil {
		return x.TargetServerId
	}
	return 0
}

func (x *SyncConf) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SyncConf) GetSourceServer() *ServerInfo {
	if x != nil {
		return x.SourceServer
	}
	return nil
}

func (x *SyncConf) GetTargetServer() *ServerInfo {
	if x != nil {
		return x.TargetServer
	}
	return nil
}

func (x *SyncConf) GetWatcherKey() string {
	if x != nil {
		return x.WatcherKey
	}
	return ""
}

func (x *SyncConf) GetSyncAllTime() int64 {
	if x != nil {
		return x.SyncAllTime
	}
	return 0
}

type SaveSyncConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceServerId int64  `protobuf:"varint,2,opt,name=source_server_id,json=sourceServerId,proto3" json:"source_server_id,omitempty"`
	TargetServerId int64  `protobuf:"varint,3,opt,name=target_server_id,json=targetServerId,proto3" json:"target_server_id,omitempty"`
	Status         int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	WatcherKey     string `protobuf:"bytes,5,opt,name=watcher_key,json=watcherKey,proto3" json:"watcher_key,omitempty"`
	SyncAllTime    int64  `protobuf:"varint,6,opt,name=sync_all_time,json=syncAllTime,proto3" json:"sync_all_time,omitempty"`
}

func (x *SaveSyncConfRequest) Reset() {
	*x = SaveSyncConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSyncConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSyncConfRequest) ProtoMessage() {}

func (x *SaveSyncConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSyncConfRequest.ProtoReflect.Descriptor instead.
func (*SaveSyncConfRequest) Descriptor() ([]byte, []int) {
	return file_sync_conf_proto_rawDescGZIP(), []int{1}
}

func (x *SaveSyncConfRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveSyncConfRequest) GetSourceServerId() int64 {
	if x != nil {
		return x.SourceServerId
	}
	return 0
}

func (x *SaveSyncConfRequest) GetTargetServerId() int64 {
	if x != nil {
		return x.TargetServerId
	}
	return 0
}

func (x *SaveSyncConfRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SaveSyncConfRequest) GetWatcherKey() string {
	if x != nil {
		return x.WatcherKey
	}
	return ""
}

func (x *SaveSyncConfRequest) GetSyncAllTime() int64 {
	if x != nil {
		return x.SyncAllTime
	}
	return 0
}

type DelSyncConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DelSyncConfRequest) Reset() {
	*x = DelSyncConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_conf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSyncConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSyncConfRequest) ProtoMessage() {}

func (x *DelSyncConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_conf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSyncConfRequest.ProtoReflect.Descriptor instead.
func (*DelSyncConfRequest) Descriptor() ([]byte, []int) {
	return file_sync_conf_proto_rawDescGZIP(), []int{2}
}

func (x *DelSyncConfRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSyncConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSyncConfRequest) Reset() {
	*x = GetSyncConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_conf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSyncConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncConfRequest) ProtoMessage() {}

func (x *GetSyncConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_conf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncConfRequest.ProtoReflect.Descriptor instead.
func (*GetSyncConfRequest) Descriptor() ([]byte, []int) {
	return file_sync_conf_proto_rawDescGZIP(), []int{3}
}

func (x *GetSyncConfRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SyncConfListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchKey string `protobuf:"bytes,1,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	Page      int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int64  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *SyncConfListRequest) Reset() {
	*x = SyncConfListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_conf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConfListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfListRequest) ProtoMessage() {}

func (x *SyncConfListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_conf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfListRequest.ProtoReflect.Descriptor instead.
func (*SyncConfListRequest) Descriptor() ([]byte, []int) {
	return file_sync_conf_proto_rawDescGZIP(), []int{4}
}

func (x *SyncConfListRequest) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *SyncConfListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SyncConfListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SyncConfListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*SyncConf `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total int64       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *SyncConfListResponse) Reset() {
	*x = SyncConfListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_conf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConfListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfListResponse) ProtoMessage() {}

func (x *SyncConfListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_conf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfListResponse.ProtoReflect.Descriptor instead.
func (*SyncConfListResponse) Descriptor() ([]byte, []int) {
	return file_sync_conf_proto_rawDescGZIP(), []int{5}
}

func (x *SyncConfListResponse) GetData() []*SyncConf {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SyncConfListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SyncConfActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status int64 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SyncConfActionRequest) Reset() {
	*x = SyncConfActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_conf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConfActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfActionRequest) ProtoMessage() {}

func (x *SyncConfActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_conf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfActionRequest.ProtoReflect.Descriptor instead.
func (*SyncConfActionRequest) Descriptor() ([]byte, []int) {
	return file_sync_conf_proto_rawDescGZIP(), []int{6}
}

func (x *SyncConfActionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncConfActionRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_sync_conf_proto protoreflect.FileDescriptor

var file_sync_conf_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x1a, 0x11,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc7, 0x02, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28,
	0x0a, 0x10, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x0d, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x5f,
	0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x73, 0x79, 0x6e, 0x63, 0x41, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x13,
	0x53, 0x61, 0x76, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x4b, 0x65, 0x79,
	0x12, 0x22, 0x0a, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x79, 0x6e, 0x63, 0x41, 0x6c, 0x6c,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x43,
	0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x65, 0x0a, 0x13, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x57, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x43,
	0x6f, 0x6e, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x65, 0x74, 0x63, 0x64, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x79, 0x6e, 0x63,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x3f, 0x0a, 0x15, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x65, 0x74, 0x63, 0x64, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_conf_proto_rawDescOnce sync.Once
	file_sync_conf_proto_rawDescData = file_sync_conf_proto_rawDesc
)

func file_sync_conf_proto_rawDescGZIP() []byte {
	file_sync_conf_proto_rawDescOnce.Do(func() {
		file_sync_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_conf_proto_rawDescData)
	})
	return file_sync_conf_proto_rawDescData
}

var file_sync_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sync_conf_proto_goTypes = []interface{}{
	(*SyncConf)(nil),              // 0: etcd_bridge.SyncConf
	(*SaveSyncConfRequest)(nil),   // 1: etcd_bridge.SaveSyncConfRequest
	(*DelSyncConfRequest)(nil),    // 2: etcd_bridge.DelSyncConfRequest
	(*GetSyncConfRequest)(nil),    // 3: etcd_bridge.GetSyncConfRequest
	(*SyncConfListRequest)(nil),   // 4: etcd_bridge.SyncConfListRequest
	(*SyncConfListResponse)(nil),  // 5: etcd_bridge.SyncConfListResponse
	(*SyncConfActionRequest)(nil), // 6: etcd_bridge.SyncConfActionRequest
	(*ServerInfo)(nil),            // 7: etcd_bridge.ServerInfo
}
var file_sync_conf_proto_depIdxs = []int32{
	7, // 0: etcd_bridge.SyncConf.source_server:type_name -> etcd_bridge.ServerInfo
	7, // 1: etcd_bridge.SyncConf.target_server:type_name -> etcd_bridge.ServerInfo
	0, // 2: etcd_bridge.SyncConfListResponse.data:type_name -> etcd_bridge.SyncConf
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sync_conf_proto_init() }
func file_sync_conf_proto_init() {
	if File_sync_conf_proto != nil {
		return
	}
	file_server_info_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sync_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSyncConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_conf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSyncConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_conf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSyncConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_conf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConfListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_conf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConfListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_conf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConfActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_conf_proto_goTypes,
		DependencyIndexes: file_sync_conf_proto_depIdxs,
		MessageInfos:      file_sync_conf_proto_msgTypes,
	}.Build()
	File_sync_conf_proto = out.File
	file_sync_conf_proto_rawDesc = nil
	file_sync_conf_proto_goTypes = nil
	file_sync_conf_proto_depIdxs = nil
}
