// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.9.0
// source: receive.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReceiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title           string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ReceiveRule     string `protobuf:"bytes,2,opt,name=receive_rule,json=receiveRule,proto3" json:"receive_rule,omitempty"`
	ReceiveServerId string `protobuf:"bytes,3,opt,name=receive_server_id,json=receiveServerId,proto3" json:"receive_server_id,omitempty"`
	ReceiveModel    int64  `protobuf:"varint,4,opt,name=receive_model,json=receiveModel,proto3" json:"receive_model,omitempty"`
	Status          int64  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	EndType         int64  `protobuf:"varint,6,opt,name=end_type,json=endType,proto3" json:"end_type,omitempty"`
	EndRule         string `protobuf:"bytes,7,opt,name=end_rule,json=endRule,proto3" json:"end_rule,omitempty"`
}

func (x *AddReceiveRequest) Reset() {
	*x = AddReceiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReceiveRequest) ProtoMessage() {}

func (x *AddReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReceiveRequest.ProtoReflect.Descriptor instead.
func (*AddReceiveRequest) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{0}
}

func (x *AddReceiveRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddReceiveRequest) GetReceiveRule() string {
	if x != nil {
		return x.ReceiveRule
	}
	return ""
}

func (x *AddReceiveRequest) GetReceiveServerId() string {
	if x != nil {
		return x.ReceiveServerId
	}
	return ""
}

func (x *AddReceiveRequest) GetReceiveModel() int64 {
	if x != nil {
		return x.ReceiveModel
	}
	return 0
}

func (x *AddReceiveRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddReceiveRequest) GetEndType() int64 {
	if x != nil {
		return x.EndType
	}
	return 0
}

func (x *AddReceiveRequest) GetEndRule() string {
	if x != nil {
		return x.EndRule
	}
	return ""
}

type GetReceiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title           string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ReceiveRule     string `protobuf:"bytes,2,opt,name=receive_rule,json=receiveRule,proto3" json:"receive_rule,omitempty"`
	ReceiveServerId string `protobuf:"bytes,3,opt,name=receive_server_id,json=receiveServerId,proto3" json:"receive_server_id,omitempty"`
	ReceiveModel    int64  `protobuf:"varint,4,opt,name=receive_model,json=receiveModel,proto3" json:"receive_model,omitempty"`
	Status          int64  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	EndType         int64  `protobuf:"varint,6,opt,name=end_type,json=endType,proto3" json:"end_type,omitempty"`
	EndRule         string `protobuf:"bytes,7,opt,name=end_rule,json=endRule,proto3" json:"end_rule,omitempty"`
}

func (x *GetReceiveRequest) Reset() {
	*x = GetReceiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiveRequest) ProtoMessage() {}

func (x *GetReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiveRequest.ProtoReflect.Descriptor instead.
func (*GetReceiveRequest) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{1}
}

func (x *GetReceiveRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetReceiveRequest) GetReceiveRule() string {
	if x != nil {
		return x.ReceiveRule
	}
	return ""
}

func (x *GetReceiveRequest) GetReceiveServerId() string {
	if x != nil {
		return x.ReceiveServerId
	}
	return ""
}

func (x *GetReceiveRequest) GetReceiveModel() int64 {
	if x != nil {
		return x.ReceiveModel
	}
	return 0
}

func (x *GetReceiveRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetReceiveRequest) GetEndType() int64 {
	if x != nil {
		return x.EndType
	}
	return 0
}

func (x *GetReceiveRequest) GetEndRule() string {
	if x != nil {
		return x.EndRule
	}
	return ""
}

type GetReceiveMessageListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiveId int64 `protobuf:"varint,1,opt,name=receive_id,json=receiveId,proto3" json:"receive_id,omitempty"`
}

func (x *GetReceiveMessageListRequest) Reset() {
	*x = GetReceiveMessageListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiveMessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiveMessageListRequest) ProtoMessage() {}

func (x *GetReceiveMessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiveMessageListRequest.ProtoReflect.Descriptor instead.
func (*GetReceiveMessageListRequest) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{2}
}

func (x *GetReceiveMessageListRequest) GetReceiveId() int64 {
	if x != nil {
		return x.ReceiveId
	}
	return 0
}

type GetReceiveMessageList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject        string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	ImapServerId   int64  `protobuf:"varint,3,opt,name=imap_server_id,json=imapServerId,proto3" json:"imap_server_id,omitempty"`
	SenderAddress  string `protobuf:"bytes,4,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	Date           string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	MessageId      string `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ImapServerText string `protobuf:"bytes,7,opt,name=imap_server_text,json=imapServerText,proto3" json:"imap_server_text,omitempty"`
	Status         uint32 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetReceiveMessageList) Reset() {
	*x = GetReceiveMessageList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiveMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiveMessageList) ProtoMessage() {}

func (x *GetReceiveMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiveMessageList.ProtoReflect.Descriptor instead.
func (*GetReceiveMessageList) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{3}
}

func (x *GetReceiveMessageList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetReceiveMessageList) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetReceiveMessageList) GetImapServerId() int64 {
	if x != nil {
		return x.ImapServerId
	}
	return 0
}

func (x *GetReceiveMessageList) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *GetReceiveMessageList) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetReceiveMessageList) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetReceiveMessageList) GetImapServerText() string {
	if x != nil {
		return x.ImapServerText
	}
	return ""
}

func (x *GetReceiveMessageList) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetReceiveMessageListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //状态码 0=失败,1=成功
	Message string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //信息
	Data    []*GetReceiveMessageList `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Count   int64                    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetReceiveMessageListResponse) Reset() {
	*x = GetReceiveMessageListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiveMessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiveMessageListResponse) ProtoMessage() {}

func (x *GetReceiveMessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiveMessageListResponse.ProtoReflect.Descriptor instead.
func (*GetReceiveMessageListResponse) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{4}
}

func (x *GetReceiveMessageListResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetReceiveMessageListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetReceiveMessageListResponse) GetData() []*GetReceiveMessageList {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetReceiveMessageListResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetReceiveMessageInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId    string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ImapServerId int64  `protobuf:"varint,3,opt,name=imap_server_id,json=imapServerId,proto3" json:"imap_server_id,omitempty"`
}

func (x *GetReceiveMessageInfoRequest) Reset() {
	*x = GetReceiveMessageInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiveMessageInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiveMessageInfoRequest) ProtoMessage() {}

func (x *GetReceiveMessageInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiveMessageInfoRequest.ProtoReflect.Descriptor instead.
func (*GetReceiveMessageInfoRequest) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{5}
}

func (x *GetReceiveMessageInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetReceiveMessageInfoRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetReceiveMessageInfoRequest) GetImapServerId() int64 {
	if x != nil {
		return x.ImapServerId
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileBytes []byte `protobuf:"bytes,1,opt,name=file_bytes,json=fileBytes,proto3" json:"file_bytes,omitempty"`
	FileName  string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{6}
}

func (x *FileInfo) GetFileBytes() []byte {
	if x != nil {
		return x.FileBytes
	}
	return nil
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetReceiveMessageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject        string      `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	ImapServerId   int64       `protobuf:"varint,3,opt,name=imap_server_id,json=imapServerId,proto3" json:"imap_server_id,omitempty"`
	SenderAddress  string      `protobuf:"bytes,4,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	Date           string      `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	MessageId      string      `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Body           string      `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Files          []*FileInfo `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty"`
	ImapServerText string      `protobuf:"bytes,9,opt,name=imap_server_text,json=imapServerText,proto3" json:"imap_server_text,omitempty"`
	Status         uint32      `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetReceiveMessageInfo) Reset() {
	*x = GetReceiveMessageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiveMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiveMessageInfo) ProtoMessage() {}

func (x *GetReceiveMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiveMessageInfo.ProtoReflect.Descriptor instead.
func (*GetReceiveMessageInfo) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{7}
}

func (x *GetReceiveMessageInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetReceiveMessageInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetReceiveMessageInfo) GetImapServerId() int64 {
	if x != nil {
		return x.ImapServerId
	}
	return 0
}

func (x *GetReceiveMessageInfo) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *GetReceiveMessageInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetReceiveMessageInfo) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetReceiveMessageInfo) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GetReceiveMessageInfo) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GetReceiveMessageInfo) GetImapServerText() string {
	if x != nil {
		return x.ImapServerText
	}
	return ""
}

func (x *GetReceiveMessageInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetReceiveMessageInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //状态码 0=失败,1=成功
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //信息
	Data    *GetReceiveMessageInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetReceiveMessageInfoResponse) Reset() {
	*x = GetReceiveMessageInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiveMessageInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiveMessageInfoResponse) ProtoMessage() {}

func (x *GetReceiveMessageInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiveMessageInfoResponse.ProtoReflect.Descriptor instead.
func (*GetReceiveMessageInfoResponse) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{8}
}

func (x *GetReceiveMessageInfoResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetReceiveMessageInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetReceiveMessageInfoResponse) GetData() *GetReceiveMessageInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddReceiveRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //状态码 0=失败,1=成功
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //信息
}

func (x *AddReceiveRequestResponse) Reset() {
	*x = AddReceiveRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReceiveRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReceiveRequestResponse) ProtoMessage() {}

func (x *AddReceiveRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReceiveRequestResponse.ProtoReflect.Descriptor instead.
func (*AddReceiveRequestResponse) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{9}
}

func (x *AddReceiveRequestResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddReceiveRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReceiveActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiveId int64 `protobuf:"varint,1,opt,name=receive_id,json=receiveId,proto3" json:"receive_id,omitempty"`
	Status    int64 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ReceiveActionRequest) Reset() {
	*x = ReceiveActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveActionRequest) ProtoMessage() {}

func (x *ReceiveActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveActionRequest.ProtoReflect.Descriptor instead.
func (*ReceiveActionRequest) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{10}
}

func (x *ReceiveActionRequest) GetReceiveId() int64 {
	if x != nil {
		return x.ReceiveId
	}
	return 0
}

func (x *ReceiveActionRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReceiveActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //状态码 0=失败,1=成功
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //信息
}

func (x *ReceiveActionResponse) Reset() {
	*x = ReceiveActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveActionResponse) ProtoMessage() {}

func (x *ReceiveActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveActionResponse.ProtoReflect.Descriptor instead.
func (*ReceiveActionResponse) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{11}
}

func (x *ReceiveActionResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReceiveActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReceiveListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page   int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Status int64 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ReceiveListRequest) Reset() {
	*x = ReceiveListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveListRequest) ProtoMessage() {}

func (x *ReceiveListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveListRequest.ProtoReflect.Descriptor instead.
func (*ReceiveListRequest) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{12}
}

func (x *ReceiveListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReceiveListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReceiveListRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReceiveList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Createtime        int64  `protobuf:"varint,3,opt,name=createtime,proto3" json:"createtime,omitempty"`
	ReceiveServerId   string `protobuf:"bytes,4,opt,name=receive_server_id,json=receiveServerId,proto3" json:"receive_server_id,omitempty"`
	Status            uint64 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ReceiveServerText string `protobuf:"bytes,6,opt,name=receive_server_text,json=receiveServerText,proto3" json:"receive_server_text,omitempty"`
}

func (x *ReceiveList) Reset() {
	*x = ReceiveList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveList) ProtoMessage() {}

func (x *ReceiveList) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveList.ProtoReflect.Descriptor instead.
func (*ReceiveList) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{13}
}

func (x *ReceiveList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReceiveList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReceiveList) GetCreatetime() int64 {
	if x != nil {
		return x.Createtime
	}
	return 0
}

func (x *ReceiveList) GetReceiveServerId() string {
	if x != nil {
		return x.ReceiveServerId
	}
	return ""
}

func (x *ReceiveList) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReceiveList) GetReceiveServerText() string {
	if x != nil {
		return x.ReceiveServerText
	}
	return ""
}

type GetReceiveListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //状态码 0=失败,1=成功
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //信息
	Data    []*ReceiveList `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Count   int64          `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetReceiveListResponse) Reset() {
	*x = GetReceiveListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receive_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiveListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiveListResponse) ProtoMessage() {}

func (x *GetReceiveListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receive_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiveListResponse.ProtoReflect.Descriptor instead.
func (*GetReceiveListResponse) Descriptor() ([]byte, []int) {
	return file_receive_proto_rawDescGZIP(), []int{14}
}

func (x *GetReceiveListResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetReceiveListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetReceiveListResponse) GetData() []*ReceiveList {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetReceiveListResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_receive_proto protoreflect.FileDescriptor

var file_receive_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xeb, 0x01, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x2a,
	0x0a, 0x11, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x22, 0xeb, 0x01,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x11,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x22, 0x3d, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x64, 0x22, 0x83, 0x02, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x24,
	0x0a, 0x0e, 0x69, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x28,
	0x0a, 0x10, 0x69, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6d, 0x61, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x8f, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x73, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x6d, 0x61, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0xb8, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x6d, 0x61,
	0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x6d, 0x61, 0x70,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x79, 0x0a, 0x1d, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x49, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x4d, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x45, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x56, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xc7,
	0x01, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x22, 0x7e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x85, 0x03, 0x0a, 0x0e, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x12, 0x2e, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x58, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x13, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_receive_proto_rawDescOnce sync.Once
	file_receive_proto_rawDescData = file_receive_proto_rawDesc
)

func file_receive_proto_rawDescGZIP() []byte {
	file_receive_proto_rawDescOnce.Do(func() {
		file_receive_proto_rawDescData = protoimpl.X.CompressGZIP(file_receive_proto_rawDescData)
	})
	return file_receive_proto_rawDescData
}

var file_receive_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_receive_proto_goTypes = []interface{}{
	(*AddReceiveRequest)(nil),             // 0: AddReceiveRequest
	(*GetReceiveRequest)(nil),             // 1: GetReceiveRequest
	(*GetReceiveMessageListRequest)(nil),  // 2: GetReceiveMessageListRequest
	(*GetReceiveMessageList)(nil),         // 3: GetReceiveMessageList
	(*GetReceiveMessageListResponse)(nil), // 4: GetReceiveMessageListResponse
	(*GetReceiveMessageInfoRequest)(nil),  // 5: GetReceiveMessageInfoRequest
	(*FileInfo)(nil),                      // 6: FileInfo
	(*GetReceiveMessageInfo)(nil),         // 7: GetReceiveMessageInfo
	(*GetReceiveMessageInfoResponse)(nil), // 8: GetReceiveMessageInfoResponse
	(*AddReceiveRequestResponse)(nil),     // 9: AddReceiveRequestResponse
	(*ReceiveActionRequest)(nil),          // 10: ReceiveActionRequest
	(*ReceiveActionResponse)(nil),         // 11: ReceiveActionResponse
	(*ReceiveListRequest)(nil),            // 12: ReceiveListRequest
	(*ReceiveList)(nil),                   // 13: ReceiveList
	(*GetReceiveListResponse)(nil),        // 14: GetReceiveListResponse
}
var file_receive_proto_depIdxs = []int32{
	3,  // 0: GetReceiveMessageListResponse.data:type_name -> GetReceiveMessageList
	6,  // 1: GetReceiveMessageInfo.files:type_name -> FileInfo
	7,  // 2: GetReceiveMessageInfoResponse.data:type_name -> GetReceiveMessageInfo
	13, // 3: GetReceiveListResponse.data:type_name -> ReceiveList
	0,  // 4: ReceiveService.AddReceive:input_type -> AddReceiveRequest
	2,  // 5: ReceiveService.GetReceiveMessages:input_type -> GetReceiveMessageListRequest
	5,  // 6: ReceiveService.GetReceiveMessageInfo:input_type -> GetReceiveMessageInfoRequest
	10, // 7: ReceiveService.ReceiveAction:input_type -> ReceiveActionRequest
	12, // 8: ReceiveService.GetReceiveList:input_type -> ReceiveListRequest
	9,  // 9: ReceiveService.AddReceive:output_type -> AddReceiveRequestResponse
	4,  // 10: ReceiveService.GetReceiveMessages:output_type -> GetReceiveMessageListResponse
	8,  // 11: ReceiveService.GetReceiveMessageInfo:output_type -> GetReceiveMessageInfoResponse
	11, // 12: ReceiveService.ReceiveAction:output_type -> ReceiveActionResponse
	14, // 13: ReceiveService.GetReceiveList:output_type -> GetReceiveListResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_receive_proto_init() }
func file_receive_proto_init() {
	if File_receive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_receive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReceiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiveMessageListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiveMessageList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiveMessageListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiveMessageInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiveMessageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiveMessageInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReceiveRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receive_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiveListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_receive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_receive_proto_goTypes,
		DependencyIndexes: file_receive_proto_depIdxs,
		MessageInfos:      file_receive_proto_msgTypes,
	}.Build()
	File_receive_proto = out.File
	file_receive_proto_rawDesc = nil
	file_receive_proto_goTypes = nil
	file_receive_proto_depIdxs = nil
}
